package com.nimbledroid.demo.toothpick;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import com.demo.toothpick.R;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import javax.inject.Inject;
import com.nimbledroid.demo.toothpick.manager.TestManager;
import com.nimbledroid.demo.toothpick.manager.TestManager10;
import com.nimbledroid.demo.toothpick.manager.TestManager11;
import com.nimbledroid.demo.toothpick.manager.TestManager12;
import com.nimbledroid.demo.toothpick.manager.TestManager13;
import com.nimbledroid.demo.toothpick.manager.TestManager14;
import com.nimbledroid.demo.toothpick.manager.TestManager15;
import com.nimbledroid.demo.toothpick.manager.TestManager2;
import com.nimbledroid.demo.toothpick.manager.TestManager3;
import com.nimbledroid.demo.toothpick.manager.TestManager4;
import com.nimbledroid.demo.toothpick.manager.TestManager5;
import com.nimbledroid.demo.toothpick.manager.TestManager6;
import com.nimbledroid.demo.toothpick.manager.TestManager7;
import com.nimbledroid.demo.toothpick.manager.TestManager8;
import com.nimbledroid.demo.toothpick.manager.TestManager9;
import com.nimbledroid.demo.toothpick.test.Test1;
import com.nimbledroid.demo.toothpick.test.Test10;
import com.nimbledroid.demo.toothpick.test.Test11;
import com.nimbledroid.demo.toothpick.test.Test12;
import com.nimbledroid.demo.toothpick.test.Test13;
import com.nimbledroid.demo.toothpick.test.Test14;
import com.nimbledroid.demo.toothpick.test.Test15;
import com.nimbledroid.demo.toothpick.test.Test16;
import com.nimbledroid.demo.toothpick.test.Test17;
import com.nimbledroid.demo.toothpick.test.Test18;
import com.nimbledroid.demo.toothpick.test.Test19;
import com.nimbledroid.demo.toothpick.test.Test2;
import com.nimbledroid.demo.toothpick.test.Test20;
import com.nimbledroid.demo.toothpick.test.Test21;
import com.nimbledroid.demo.toothpick.test.Test22;
import com.nimbledroid.demo.toothpick.test.Test23;
import com.nimbledroid.demo.toothpick.test.Test24;
import com.nimbledroid.demo.toothpick.test.Test25;
import com.nimbledroid.demo.toothpick.test.Test26;
import com.nimbledroid.demo.toothpick.test.Test27;
import com.nimbledroid.demo.toothpick.test.Test28;
import com.nimbledroid.demo.toothpick.test.Test29;
import com.nimbledroid.demo.toothpick.test.Test3;
import com.nimbledroid.demo.toothpick.test.Test30;
import com.nimbledroid.demo.toothpick.test.Test31;
import com.nimbledroid.demo.toothpick.test.Test32;
import com.nimbledroid.demo.toothpick.test.Test33;
import com.nimbledroid.demo.toothpick.test.Test34;
import com.nimbledroid.demo.toothpick.test.Test35;
import com.nimbledroid.demo.toothpick.test.Test36;
import com.nimbledroid.demo.toothpick.test.Test37;
import com.nimbledroid.demo.toothpick.test.Test38;
import com.nimbledroid.demo.toothpick.test.Test39;
import com.nimbledroid.demo.toothpick.test.Test4;
import com.nimbledroid.demo.toothpick.test.Test40;
import com.nimbledroid.demo.toothpick.test.Test5;
import com.nimbledroid.demo.toothpick.test.Test6;
import com.nimbledroid.demo.toothpick.test.Test7;
import com.nimbledroid.demo.toothpick.test.Test8;
import com.nimbledroid.demo.toothpick.test.Test9;
import toothpick.Injector;
import toothpick.ToothPick;
import toothpick.registries.factory.FactoryRegistryLocator;
import toothpick.registries.memberinjector.MemberInjectorRegistryLocator;

public class MainActivity extends Activity {

    @Inject Test1 mTest1;
    @Inject Test2 mTest2;
    @Inject Test3 mTest3;
    @Inject Test4 mTest4;
    @Inject Test5 mTest5;
    @Inject Test6 mTest6;
    @Inject Test7 mTest7;
    @Inject Test8 mTest8;
    @Inject Test9 mTest9;
    @Inject Test10 mTest10;
    @Inject Test11 mTest11;
    @Inject Test12 mTest12;
    @Inject Test13 mTest13;
    @Inject Test14 mTest14;
    @Inject Test15 mTest15;
    @Inject Test16 mTest16;
    @Inject Test17 mTest17;
    @Inject Test18 mTest18;
    @Inject Test19 mTest19;
    @Inject Test20 mTest20;
    @Inject Test21 mTest21;
    @Inject Test22 mTest22;
    @Inject Test23 mTest23;
    @Inject Test24 mTest24;
    @Inject Test25 mTest25;
    @Inject Test26 mTest26;
    @Inject Test27 mTest27;
    @Inject Test28 mTest28;
    @Inject Test29 mTest29;
    @Inject Test30 mTest30;
    @Inject Test31 mTest31;
    @Inject Test32 mTest32;
    @Inject Test33 mTest33;
    @Inject Test34 mTest34;
    @Inject Test35 mTest35;
    @Inject Test36 mTest36;
    @Inject Test37 mTest37;
    @Inject Test38 mTest38;
    @Inject Test39 mTest39;
    @Inject Test40 mTest40;

    @Inject Future<TestManager> mTestManager;
    @Inject Future<TestManager2> mTestManager2;
    @Inject Future<TestManager3> mTestManager3;
    @Inject Future<TestManager4> mTestManager4;
    @Inject Future<TestManager5> mTestManager5;
    @Inject Future<TestManager6> mTestManager6;
    @Inject Future<TestManager7> mTestManager7;
    @Inject Future<TestManager8> mTestManager8;
    @Inject Future<TestManager9> mTestManager9;
    @Inject Future<TestManager10> mTestManager10;
    @Inject Future<TestManager11> mTestManager11;
    @Inject Future<TestManager12> mTestManager12;
    @Inject Future<TestManager13> mTestManager13;
    @Inject Future<TestManager14> mTestManager14;
    @Inject Future<TestManager15> mTestManager15;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        long start = System.currentTimeMillis();
        final Injector injector = ToothPick.createInjector(null, this);
        MemberInjectorRegistryLocator.addRegistry(new com.nimbledroid.demo.toothpick.MemberInjectorRegistry());
        FactoryRegistryLocator.addRegistry(new com.nimbledroid.demo.toothpick.FactoryRegistry());
        long end = System.currentTimeMillis();
        System.out.println("Time to setup activity injector " + (end-start));
        injector.inject(this);
        long end2 = System.currentTimeMillis();
        System.out.println("Time to inject members" + (end2 - end));

        setContentView(R.layout.activity_main);

        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest1.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest2.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest3.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest4.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest5.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest6.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest7.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest8.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest9.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest10.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest11.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest12.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest13.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest14.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest15.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest16.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest17.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest18.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest19.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest20.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest21.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest22.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest23.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest24.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest25.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest26.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest27.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest28.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest29.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest30.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest31.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest32.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest33.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest34.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest35.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest36.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest37.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest38.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest39.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest40.toString());

        try {
            mTestManager.get().start();
            mTestManager2.get().start();
            mTestManager3.get().start();
            mTestManager4.get().start();
            mTestManager5.get().start();
            mTestManager6.get().start();
            mTestManager7.get().start();
            mTestManager8.get().start();
            mTestManager9.get().start();
            mTestManager10.get().start();
            mTestManager11.get().start();
            mTestManager12.get().start();
            mTestManager13.get().start();
            mTestManager14.get().start();
            mTestManager15.get().start();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
    }
}
