package com.nimbledroid.demo.dagger1.test;

import javax.inject.Inject;
import model.a.A1;
import model.a.A10;
import model.a.A11;
import model.a.A12;
import model.a.A13;
import model.a.A14;
import model.a.A15;
import model.a.A16;
import model.a.A17;
import model.a.A18;
import model.a.A19;
import model.a.A2;
import model.a.A20;
import model.a.A3;
import model.a.A4;
import model.a.A5;
import model.a.A6;
import model.a.A7;
import model.a.A8;
import model.a.A9;
import model.b.B1;
import model.b.B10;
import model.b.B11;
import model.b.B12;
import model.b.B13;
import model.b.B14;
import model.b.B15;
import model.b.B16;
import model.b.B17;
import model.b.B18;
import model.b.B19;
import model.b.B2;
import model.b.B20;
import model.b.B3;
import model.b.B4;
import model.b.B5;
import model.b.B6;
import model.b.B7;
import model.b.B8;
import model.b.B9;
import model.c.C1;
import model.c.C10;
import model.c.C11;
import model.c.C12;
import model.c.C13;
import model.c.C14;
import model.c.C15;
import model.c.C16;
import model.c.C17;
import model.c.C18;
import model.c.C19;
import model.c.C2;
import model.c.C20;
import model.c.C3;
import model.c.C4;
import model.c.C5;
import model.c.C6;
import model.c.C7;
import model.c.C8;
import model.c.C9;
import model.d.D1;
import model.d.D10;
import model.d.D11;
import model.d.D12;
import model.d.D13;
import model.d.D14;
import model.d.D15;
import model.d.D16;
import model.d.D17;
import model.d.D18;
import model.d.D19;
import model.d.D2;
import model.d.D20;
import model.d.D3;
import model.d.D4;
import model.d.D5;
import model.d.D6;
import model.d.D7;
import model.d.D8;
import model.d.D9;
import model.e.E1;
import model.e.E10;
import model.e.E11;
import model.e.E12;
import model.e.E13;
import model.e.E14;
import model.e.E15;
import model.e.E16;
import model.e.E17;
import model.e.E18;
import model.e.E19;
import model.e.E2;
import model.e.E20;
import model.e.E3;
import model.e.E4;
import model.e.E5;
import model.e.E6;
import model.e.E7;
import model.e.E8;
import model.e.E9;

public class Test1 {

    @Inject public A1 a1;
    @Inject public A2 a2;
    @Inject public A3 a3;
    @Inject public A4 a4;
    @Inject public A5 a5;
    @Inject public A6 a6;
    @Inject public A7 a7;
    @Inject public A8 a8;
    @Inject public A9 a9;
    @Inject public A10 a10;
    @Inject public A11 a11;
    @Inject public A12 a12;
    @Inject public A13 a13;
    @Inject public A14 a14;
    @Inject public A15 a15;
    @Inject public A16 a16;
    @Inject public A17 a17;
    @Inject public A18 a18;
    @Inject public A19 a19;
    @Inject public A20 a20;

    @Inject public B1 b1;
    @Inject public B2 b2;
    @Inject public B3 b3;
    @Inject public B4 b4;
    @Inject public B5 b5;
    @Inject public B6 b6;
    @Inject public B7 b7;
    @Inject public B8 b8;
    @Inject public B9 b9;
    @Inject public B10 b10;
    @Inject public B11 b11;
    @Inject public B12 b12;
    @Inject public B13 b13;
    @Inject public B14 b14;
    @Inject public B15 b15;
    @Inject public B16 b16;
    @Inject public B17 b17;
    @Inject public B18 b18;
    @Inject public B19 b19;
    @Inject public B20 b20;

    @Inject public C1 c1;
    @Inject public C2 c2;
    @Inject public C3 c3;
    @Inject public C4 c4;
    @Inject public C5 c5;
    @Inject public C6 c6;
    @Inject public C7 c7;
    @Inject public C8 c8;
    @Inject public C9 c9;
    @Inject public C10 c10;
    @Inject public C11 c11;
    @Inject public C12 c12;
    @Inject public C13 c13;
    @Inject public C14 c14;
    @Inject public C15 c15;
    @Inject public C16 c16;
    @Inject public C17 c17;
    @Inject public C18 c18;
    @Inject public C19 c19;
    @Inject public C20 c20;

    @Inject public D1 d1;
    @Inject public D2 d2;
    @Inject public D3 d3;
    @Inject public D4 d4;
    @Inject public D5 d5;
    @Inject public D6 d6;
    @Inject public D7 d7;
    @Inject public D8 d8;
    @Inject public D9 d9;
    @Inject public D10 d10;
    @Inject public D11 d11;
    @Inject public D12 d12;
    @Inject public D13 d13;
    @Inject public D14 d14;
    @Inject public D15 d15;
    @Inject public D16 d16;
    @Inject public D17 d17;
    @Inject public D18 d18;
    @Inject public D19 d19;
    @Inject public D20 d20;

    @Inject public E1 e1;
    @Inject public E2 e2;
    @Inject public E3 e3;
    @Inject public E4 e4;
    @Inject public E5 e5;
    @Inject public E6 e6;
    @Inject public E7 e7;
    @Inject public E8 e8;
    @Inject public E9 e9;
    @Inject public E10 e10;
    @Inject public E11 e11;
    @Inject public E12 e12;
    @Inject public E13 e13;
    @Inject public E14 e14;
    @Inject public E15 e15;
    @Inject public E16 e16;
    @Inject public E17 e17;
    @Inject public E18 e18;
    @Inject public E19 e19;
    @Inject public E20 e20;
}